
-- ShonellesEZevents Orders v1
create extension if not exists pgcrypto;

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null default ('SEZ-' || upper(substr(replace(gen_random_uuid()::text,'-',''),1,8))),
  customer_name text not null,
  contact text not null,
  customization text default '',
  fulfillment text default 'Not sure yet',
  notes text default '',
  estimated_total numeric(10,2) not null default 0,
  status text not null default 'New'
    check (status in ('New','Awaiting Payment','Paid','In Production','Ready','Shipped/Completed','Cancelled')),
  payment_status text not null default 'Not started',
  payment_reference text default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id text,
  product_name text not null,
  unit_price numeric(10,2) not null default 0,
  quantity integer not null default 1 check (quantity > 0)
);

alter table public.orders enable row level security;
alter table public.order_items enable row level security;

drop policy if exists "Anyone can submit an order request" on public.orders;
create policy "Anyone can submit an order request"
on public.orders for insert to anon, authenticated
with check (status = 'New' and payment_status = 'Not started');

drop policy if exists "Admins can read orders" on public.orders;
create policy "Admins can read orders"
on public.orders for select to authenticated using (true);

drop policy if exists "Admins can update orders" on public.orders;
create policy "Admins can update orders"
on public.orders for update to authenticated using (true) with check (true);

drop policy if exists "Anyone can submit order items" on public.order_items;
create policy "Anyone can submit order items"
on public.order_items for insert to anon, authenticated
with check (true);

drop policy if exists "Admins can read order items" on public.order_items;
create policy "Admins can read order items"
on public.order_items for select to authenticated using (true);
